# Generated by Django 5.2.16 on 2026-07-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kundli', '0002_alter_birthdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdetails',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthdetails',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='birthdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
