# Generated by Django 5.2.16 on 2026-07-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kundli', '0003_birthdetails_gender_birthdetails_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
