TITHIS = [
    "Pratipada",
    "Dwitiya",
    "Tritiya",
    "Chaturthi",
    "Panchami",
    "Shashthi",
    "Saptami",
    "Ashtami",
    "Navami",
    "Dashami",
    "Ekadashi",
    "Dwadashi",
    "Trayodashi",
    "Chaturdashi",
    "Purnima",
    "Pratipada Krishna",
    "Dwitiya Krishna",
    "Tritiya Krishna",
    "Chaturthi Krishna",
    "Panchami Krishna",
    "Shashthi Krishna",
    "Saptami Krishna",
    "Ashtami Krishna",
    "Navami Krishna",
    "Dashami Krishna",
    "Ekadashi Krishna",
    "Dwadashi Krishna",
    "Trayodashi Krishna",
    "Chaturdashi Krishna",
    "Amavasya",
]
NAKSHATRAS = [
    "Ashwini",
    "Bharani",
    "Krittika",
    "Rohini",
    "Mrigashira",
    "Ardra",
    "Punarvasu",
    "Pushya",
    "Ashlesha",
    "Magha",
    "Purva Phalguni",
    "Uttara Phalguni",
    "Hasta",
    "Chitra",
    "Swati",
    "Vishakha",
    "Anuradha",
    "Jyeshtha",
    "Mula",
    "Purva Ashadha",
    "Uttara Ashadha",
    "Shravana",
    "Dhanishta",
    "Shatabhisha",
    "Purva Bhadrapada",
    "Uttara Bhadrapada",
    "Revati",
]